name: Deploy to GitHub Pages Another Way

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Display current directory
        run: pwd

      - name: List root directory contents
        run: ls -al

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: List node and npm versions
        run: |
          node -v
          npm -v

      - name: Build the React app
        run: npm run build

      - name: List dist directory contents
        run: ls -al dist

  #    - name: Checkout to gh-pages branch
  #      uses: actions/checkout@v2
  #      with:
  #          ref: gh-pages   
  #      
  #      -name: Delete all files from branch
  #      run: |
  #              rm -rf .
  #              git add -A
  #              git commit -m "Remove files from gh-pages branch"

#        -name: Push Changes to gh-pages branch  
#        uses: ad-m/github-push-action@v0.6.0
#              with: 
#                github_token:   ${{secrets.GITHUB_TOKEN}}
#                branch: gh-pages

      - name: Install GitHub Pages
        run:  npm install gh-pages

      - name: Deploy to GitHub Pages
        run:  npm run build && gh-pages -d dist